version: '3.8'

services:
  moodleapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: moodle-web:1.0
    container_name: moodle-web
    ports:
      - 8080:80
    volumes:
      - moodledata:/var/www/moodledata
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle_user
      - MYSQL_PASSWORD=moodle_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "81:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root_password
    depends_on:
      - mysql

volumes:
  mysqldata:
  moodledata: